version: '2'

services:
    app:
        image: arquiteturansj/flask:2.2
        restart: always
        ports:
            - "5000:80"
            - "5678:5678"
        volumes:
            - $PWD:/var/www/html
            - $PWD/wsgi_dev.ini:/etc/wsgi/wsgi.ini
            - $PWD/logs:/var/log/nasajon
        env_file:
            - .env
        command: sh -c "python3 -m pip install -r /var/www/html/requirements.txt --no-cache-dir && /entrypoint.sh"

    postgres:
        image: postgres:11.5
        ports:
            - "5440:5432"
        restart: always
        volumes:
            - $PWD/database/dump:/docker-entrypoint-initdb.d/
            - $PWD/database/data:/var/lib/postgresql/data
        environment:
            - "POSTGRES_DB=projeto"
            - "POSTGRES_USER=projeto"
            - "POSTGRES_PASSWORD=mysecretpassword"

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        restart: always
        environment:
            - RABBITMQ_DEFAULT_VHOST=skeleton

    async_order_worker:
        image: arquiteturansj/flask:2.2
        restart: always
        volumes:
            - $PWD:/var/www/html
            - $PWD/logs/worker:/var/log/nasajon
        env_file:
            - .env
        command: sh -c "python3 -m pip install -r /var/www/html/requirements.txt --no-cache-dir && python3 -m nasajon.worker.async_order_worker"

    # Bancos alternativos (MySQL e SingleStore) - Caso necessário (mas, a implementação padrão nãos os utiliza)
    mysql:
        image: mysql:8.0.30
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - $PWD/database/dump:/docker-entrypoint-initdb.d/
            - $PWD/database/data:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=projeto"
            - "MYSQL_USER=projeto"
            - "MYSQL_PASSWORD=mysecretpassword"
            - "MYSQL_ROOT_PASSWORD=rootsecretpassword"

    memsql:
        build: ./database/memsql
        ports:
            - 3306:3306
            - 8080:8080
        volumes:
            - ./database/dump:/data
        #   - memsql-data:/var/lib/memsql
        environment:
            - ROOT_PASSWORD=nasajon
            - LICENSE_KEY=BDI5N2M0N2M1NWNkZTQzNmFiMTU1ZTEzMjNmY2JiMDJmAAAAAAAAAAAEAAAAAAAAAAwwNQIYIN/Bhr8jwJApNG6mq1aHI3Ep0ugzTkaRAhkA4ImSi5m0cfJmYn87YfNbc8Hp8LhlAwJbAA==

