version: '2'

services:
    # app:
    #     image: nasajon/php:7.1-fpm-symfony-dev
    #     restart: always
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - $PWD:/var/www/html        
    #     env_file:
    #         - common.env

    postgres:
       image: postgres:11.5
       ports:
         - "5440:5432"
       restart: always
       volumes:
           - $PWD/database/dump:/docker-entrypoint-initdb.d/
       environment:
           - "POSTGRES_DB=projeto"
           - "POSTGRES_USER=projeto"
           - "POSTGRES_PASSWORD=mysecretpassword"  
