version: '2'

services:
    app:
        image: arquiteturansj/flask:2.2
        restart: always
        ports:
            - "5000:80"
            - "5678:5678"
        volumes:
            - $PWD:/var/www/html
            - $PWD/wsgi_dev.ini:/etc/wsgi/wsgi.ini
            - $PWD/logs:/var/log/nasajon
        env_file:
            - .env
        command: sh -c "python3 -m pip install -r /var/www/html/requirements.txt --no-cache-dir && /entrypoint.sh"

    postgres:
        image: postgres:11.5
        ports:
            - "5440:5432"
        restart: always
        volumes:
            - $PWD/database/dump:/docker-entrypoint-initdb.d/
        environment:
            - "POSTGRES_DB=projeto"
            - "POSTGRES_USER=projeto"
            - "POSTGRES_PASSWORD=mysecretpassword"

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        restart: always
        environment:
            - RABBITMQ_DEFAULT_VHOST=skeleton

    async_order_worker:
        image: arquiteturansj/flask:2.2
        restart: always
        volumes:
            - $PWD:/var/www/html
            - $PWD/logs/worker:/var/log/nasajon
        env_file:
            - .env
        command: sh -c "python3 -m pip install -r /var/www/html/requirements.txt --no-cache-dir && python3 -m nasajon.worker.async_order_worker"
