version: '2'

services:
    app:
        image: arquiteturansj/flask:2.2
        restart: always
        ports:
            - "80:80"
            - "5678:5678"
        volumes:
            - $PWD:/var/www/html
            - $PWD/wsgi_dev.ini:/etc/wsgi/wsgi.ini
        env_file:
            - .env
        command: sh -c "python3 -m pip install -r /var/www/html/requirements.txt --no-cache-dir && /entrypoint.sh"

    postgres:
        image: postgres:11.5
        ports:
            - "5440:5432"
        restart: always
        volumes:
            - $PWD/database/dump:/docker-entrypoint-initdb.d/
        environment:
            - "POSTGRES_DB=projeto"
            - "POSTGRES_USER=projeto"
            - "POSTGRES_PASSWORD=mysecretpassword"
