########################################
# Autenticação para token off-line DEV #
########################################
POST https://auth.dev.nasajonsistemas.com.br/auth/realms/DEV/protocol/openid-connect/token HTTP/1.1
content-type: application/x-www-form-urlencoded

client_id=erp_api&scope=offline_access&grant_type=password&username=wallacepinho%40nasajon.com.br&password=123456

#######################################
# Autenticação para token off-line QA #
#######################################
POST https://auth.nasajonsistemas.com.br/auth/realms/QA/protocol/openid-connect/token HTTP/1.1
content-type: application/x-www-form-urlencoded

client_id=erp_api&scope=offline_access&grant_type=password&username=wallacepinho%40nasajon.com.br&password=123456

#########################################
# Autenticação para token off-line PROD #
#########################################
POST https://auth.nasajon.com.br/auth/realms/master/protocol/openid-connect/token HTTP/1.1
content-type: application/x-www-form-urlencoded

client_id=cadastro_geral&scope=offline_access&grant_type=password&username=sergiosilva%40nasajon.com.br&password=*******
