########################
# Get list de Clientes #
########################
GET http://localhost:5000/app/1234/clientes HTTP/1.1
Authorization: Bearer ***********
Accept: application/json

######################
# Get Clientes ILIKE #
######################
GET http://localhost:5000/app/1234/clientes?search=Fulano HTTP/1.1
Authorization: Bearer ***********
Accept: application/json

#####################
# Get Cliente by ID #
#####################
GET http://localhost:5000/app/1234/clientes/d5c29f81-fc11-4a0e-a742-5e1024664ad5 HTTP/1.1
Authorization: Bearer ***********
Accept: application/json

################
# POST Cliente #
################
POST http://localhost:5000/app/1234/clientes HTTP/1.1
Authorization: Bearer ***********
Content-Type: application/json
Accept: application/json

{
    "nome": "Beltrano",
    "documento": "987789654456"
}