########
# Ping #
########
GET http://localhost:5000/ping HTTP/1.1
X-API-Key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzaXN0ZW1hIjozMTMsInRpcG8iOiJzaXN0ZW1hIn0.-NyjvdNNsWiwLzmU6NoOVCgJJk4rj2TBsGB8K_Vge8g
Accept: application/json
